# -*- python -*-

#env = Environment(CPPPATH=['#include'], CCFLAGS=['-g', '-Wall'])
#env = Environment(CPPPATH=["#include/path", 'C:/cppunit/cppunit-1.12.0/include'],
#					CPPFLAGS='/EHsc')
Import("env")
env.Program(target = 'pathtest',
            source =
            ['main.cpp',
             'CanonicalUnit.cpp',
	     'ExpandUnit.cpp',
             'GlobUnit.cpp',
             'NodeUnit.cpp',
	     'PathLookupUnit.cpp',
             'PathRulesUnit.cpp',
             'PathUnit.cpp',
             'RefcountUnit.cpp',
             'SysCallsUnit.cpp',
             'UnixRulesUnit.cpp',
             'Win32RulesUnit.cpp'
             ],
            LIBS = ['path', 'cppunit', 'dl'],
            LIBPATH = ['../../src'])
